site_name: Google Sheets User Guide
site_url: https://sitename.example
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - toc.integrate

nav:
  - Home: "index.md"
  - Functions: "Functions.md"
  - Sorting & Formatting: "SortingFormatting.md"
  - Linear Regression Graphs: "LinearRegression.md"
  - Troubleshooting: "Troubleshooting.md"
  - Glossary: "Glossary.md"

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true